---
- name: Install everything
  hosts: localhost
  connection: local
  strategy: debug
  roles:
  - role: ansible-download-directory

  - role: zsh
  - role: homebrew
  - role: dotfiles

  - role: software
    tags:
      - software

  - role: iterm

